# Generated by Django 4.1.7 on 2023-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('years', models.CharField(max_length=255, verbose_name='Год')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манги',
            },
        ),
    ]
